In [5]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/paradox/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [3]:
import numpy as np
from nltk import word_tokenize


In [4]:
sentence= "Transfomers are easy to understand and implement"

In [5]:
sentence=sentence.lower()
tokens=word_tokenize(sentence)
print(tokens)

['transfomers', 'are', 'easy', 'to', 'understand', 'and', 'implement']


In [6]:
embedding_dim=4
np.random.seed(42)

In [7]:
word_embeddings={}
for word in sorted(list(set(tokens))):
    word_embeddings[word]=np.random.rand(embedding_dim)*2-1

print(word_embeddings)

{'and': array([-0.25091976,  0.90142861,  0.46398788,  0.19731697]), 'are': array([-0.68796272, -0.68801096, -0.88383278,  0.73235229]), 'easy': array([ 0.20223002,  0.41614516, -0.95883101,  0.9398197 ]), 'implement': array([ 0.66488528, -0.57532178, -0.63635007, -0.63319098]), 'to': array([-0.39151551,  0.04951286, -0.13610996, -0.41754172]), 'transfomers': array([ 0.22370579, -0.72101228, -0.4157107 , -0.26727631]), 'understand': array([-0.08786003,  0.57035192, -0.60065244,  0.02846888])}


In [9]:
temp = []
for token in tokens:
    temp.append(word_embeddings[token])
X= np.array(temp)
print(X)

[[ 0.22370579 -0.72101228 -0.4157107  -0.26727631]
 [-0.68796272 -0.68801096 -0.88383278  0.73235229]
 [ 0.20223002  0.41614516 -0.95883101  0.9398197 ]
 [-0.39151551  0.04951286 -0.13610996 -0.41754172]
 [-0.08786003  0.57035192 -0.60065244  0.02846888]
 [-0.25091976  0.90142861  0.46398788  0.19731697]
 [ 0.66488528 -0.57532178 -0.63635007 -0.63319098]]


In [16]:
query_dim = 3
np.random.seed(10)
Wq=np.random.rand(embedding_dim,query_dim)*0.1
print(Wq)

[[0.07713206 0.00207519 0.06336482]
 [0.07488039 0.0498507  0.02247966]
 [0.01980629 0.07605307 0.01691108]
 [0.00883398 0.06853598 0.09533933]]


In [14]:
Q = X @ Wq
print(Q)

[[-0.04732959 -0.08541285 -0.0345451 ]
 [-0.11561837 -0.0527512  -0.00418348]
 [ 0.036071    0.01265422  0.09555599]
 [-0.03287525 -0.03731243 -0.0658052 ]
 [ 0.02428615 -0.0154802  -0.0001894 ]
 [ 0.05907834  0.09322716  0.03102293]
 [-0.00999367 -0.11909317 -0.04193208]]


In [19]:

np.random.seed(20)
Wk=np.random.rand(embedding_dim,query_dim)*0.1
print(Wk)

[[0.05881308 0.08977137 0.08915307]
 [0.08158375 0.00358896 0.06917576]
 [0.03786809 0.05185109 0.06579515]
 [0.01938502 0.02723164 0.07186059]]


In [20]:
K = X @ Wk
print(K)

[[-0.06658939 -0.01133873 -0.07649089]
 [-0.11586412 -0.09011314 -0.11445231]
 [ 0.02775377 -0.00447561  0.05126616]
 [-0.03223507 -0.05339698 -0.07043989]
 [ 0.01917044 -0.03620958 -0.00585269]
 [ 0.08017989  0.01014132  0.08469421]
 [-0.04420474  0.00738458 -0.06789198]]


In [21]:
np.random.seed(30)
Wv=np.random.rand(embedding_dim,query_dim)*0.1
print(Wv)

[[0.06441435 0.03807485 0.06630479]
 [0.01636507 0.09626078 0.03466618]
 [0.0991751  0.02350579 0.05856943]
 [0.04066901 0.01362343 0.05441363]]


In [22]:
V= X @ Wv
print(V)

[[-0.04948757 -0.07430047 -0.04905339]
 [-0.11344418 -0.10322058 -0.08138157]
 [-0.03703386  0.03802383  0.0228158 ]
 [-0.05488866 -0.01902847 -0.05493477]
 [-0.05473756  0.0378263  -0.01968439]
 [ 0.05262984  0.09081303  0.05252414]
 [-0.05544836 -0.05364966 -0.04758401]]


In [25]:
mata= np.dot(Q,K.T)
mata=mata/np.sqrt(query_dim)


In [52]:
def softmax(x,axis=-1):
    exp_x = np.exp(x - np.max(x,axis=axis, keepdims=True))  
    return exp_x / np.sum(exp_x,axis=axis, keepdims=True)

In [53]:
tt=softmax(mata)
print(tt)

[[0.14308007 0.14393943 0.14230034 0.14322531 0.14271913 0.1418996
  0.14283611]
 [0.14326671 0.1440972  0.14229364 0.14311966 0.14253252 0.14172199
  0.14296828]
 [0.14235014 0.14182499 0.14364615 0.14245581 0.14313542 0.1440839
  0.14250359]
 [0.14320316 0.14378783 0.14223377 0.14320661 0.14266348 0.14186728
  0.14303787]
 [0.14274424 0.14274671 0.14292243 0.14286662 0.14294666 0.14300832
  0.14276502]
 [0.14260851 0.1416703  0.14344889 0.14246831 0.14301577 0.14390487
  0.14288334]
 [0.14292316 0.14387241 0.14233707 0.14328767 0.14285245 0.14203609
  0.14269114]]


In [58]:
sum=0.0
for i in tt:
    for t in i:
        sum+=t
    print(sum)
    sum=0.0

1.0
0.9999999999999999
1.0000000000000002
1.0
0.9999999999999999
1.0000000000000002
0.9999999999999999


In [59]:
Z = tt @ V  
print(Z)

[[-0.04480512 -0.01218122 -0.02550683]
 [-0.04483267 -0.0122399  -0.02553512]
 [-0.04442612 -0.01161097 -0.02510362]
 [-0.04480037 -0.01219276 -0.02551123]
 [-0.04460671 -0.01188957 -0.02530226]
 [-0.04443867 -0.0116631  -0.02513401]
 [-0.04478662 -0.01213722 -0.02548483]]
